version: "3"
tasks:
  default:
    cmds:
      - task --list
    silent: true

  build:
    desc: "build container"
    silent: true
    cmds:
      - docker build --pull --no-cache -t kloot:latest .
      - docker run -it kloot:latest claude --version
      - docker run -it kloot:latest glab --version
      - docker run -it kloot:latest sh -c 'gopls version && golangci-lint version && mockery version && shfmt --version && python3 --version && shellcheck --version && make --version'

  sh:
    desc: "build container"
    silent: true
    cmds:
      - docker run --rm -it kloot:latest bash

  install:
    desc: "install kloot command"
    silent: true
    cmds:
      - touch ~/.kloot/.claude.json
      - echo "Creating symlink to /usr/local/bin/kloot (needs sudo permissions)"
      - sudo ln -s "$(pwd)/kloot" /usr/local/bin/kloot

